/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-gray-200',
    'bg-gray-800',
    'text-gray-900',
    'text-gray-800',
    'text-gray-700',
    'text-gray-600',
    'text-gray-500',
    'text-yellow-600',
    'text-orange-500',
    'text-blue-600',
    'text-purple-600',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'border',
    'border-gray-300',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'md:grid-cols-2',
    'gap-4',
    'gap-8',
    'text-center',
    'text-left',
    'py-3',
    'py-4',
    'py-6',
    'py-8',
    'px-4',
    'px-6',
    'px-8',
    'p-4',
    'p-6',
    'p-8',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-12',
    'mt-4',
    'space-y-4',
    'flex',
    'flex-1',
    'items-center',
    'justify-center',
    'w-full',
    'max-w-md',
    'max-w-lg',
    'max-w-2xl',
    'max-w-4xl',
    'mx-auto',
    'font-semibold',
    'font-bold',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'cursor-pointer',
    'cursor-not-allowed',
    'transition-all',
    'transition-colors',
    'hover:shadow-xl',
    'hover:bg-gray-700',
    'pt-24',
    'pb-8',
    'min-h-screen',
    'fixed',
    'inset-0',
    'z-50',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#1a1a2e',
          light: '#2a2a4e',
          dark: '#0f0f1a',
        },
        gold: {
          DEFAULT: '#d4af37',
          light: '#e4cf67',
          dark: '#b49f27',
        },
        sunset: {
          DEFAULT: '#ff6b35',
          light: '#ff8b55',
          dark: '#df4b15',
        },
      },
      fontFamily: {
        serif: ['Noto Serif SC', 'serif'],
        sans: ['Noto Sans SC', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(212, 175, 55, 0.5)' },
          '100%': { boxShadow: '0 0 20px rgba(212, 175, 55, 0.8)' },
        },
      },
    },
  },
  plugins: [],
}
